### ISSUE TITLE
fix vow dependency

### ISSUE THREAD

**Issue by rifler** [enb-make/enb-async-require#5]
`"vow": "^0.4.10"`

`^` means [keep major version](https://docs.npmjs.com/getting-started/semantic-versioning)

In this case `0.5.0`, `0.6.0` and so on fit this definition

**Comment by j0tunn** [comment]
Take a look here: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

> Allows changes that do not modify the **left-most non-zero digit** in the [major, minor, patch] tuple

**Comment by rifler** [comment]
oh, you are right!
